from .auth import *
from .main import *

from .transactions import *
from .service import *
from .partner import *
from .service_type import *
from .service_tariff import *
from .service_info import *
from .resource import *
from .partners import *
from .partner_info import *
from .provider import *
from .cooperate import *
from .payment import *
from .balance import *
from .trans_id import *
from .schema import *
from .user_info import *
from .get_userid import *