from .index import index
from .transactions import transactions
#from .context import get_context
from .service import *
from .service_type import *
from .service_tariff import *
from .service_info import *
from .resource import *
from .partners import *
from .partner_info import *
from .provider import *
from .login import *
from .test import testPage
from .balance import balance
from .trans_id import trans_id
from .schema import schema_v3